<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <RootNamespace>Dramaturge.TestUtilities</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PinchHitter" Version="0.0.20" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WebDriverBiDi" Version="0.0.63" />
  </ItemGroup>

</Project>
